---

x-logging: &logging
  driver: json-file
  options:
    max-size: 10m

services:
  klipper:
    container_name: ${COMPOSE_PROJECT_NAME}-klipper
    hostname: ${COMPOSE_PROJECT_NAME} # Klipper reports the hostname as printer name
    image: mkuf/klipper:latest
    privileged: true
    restart: unless-stopped
    logging: *logging
    volumes:
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - ./common:/opt/printer_data/common

  moonraker:
    build:
      context: .
      dockerfile_inline: |
        FROM mkuf/moonraker
        USER root
        RUN apt install -y ffmpeg wget
        ADD --keep-git-dir=true https://github.com/mainsail-crew/moonraker-timelapse.git /opt/moonraker-timelapse
        RUN chown -R moonraker:moonraker /opt/moonraker-timelapse
        USER moonraker
        RUN ln -s /opt/moonraker-timelapse/component/timelapse.py /opt/moonraker/moonraker/components/timelapse.py
        RUN ln -s /opt/printer_data/common/moonraker.secrets /opt/printer_data/moonraker.secrets
    container_name: ${COMPOSE_PROJECT_NAME}-moonraker
    privileged: true
    pid: host
    restart: unless-stopped
    logging: *logging
    volumes:
      - /dev/null:/opt/klipper/config/null # wtf?
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - ./common:/opt/printer_data/common

  telegram:
    container_name: ${COMPOSE_PROJECT_NAME}-telegram
    image: lefskiy/moonraker-telegram-bot:latest
    restart: unless-stopped
    logging: *logging
    volumes:
      - ./common:/opt/printer_data/common

  ustreamer:
    container_name: ${COMPOSE_PROJECT_NAME}-ustreamer
    image: mkuf/ustreamer:latest
    restart: unless-stopped
    command: >
      --host=0.0.0.0
      --slowdown
      --device=/dev/webcam
      --resolution=800x600
      --format=MJPEG
      --desired-fps=10
      --device-timeout=8
      --allow-origin=*
    logging: *logging

